#!/bin/bash
# Install Aether UI to a system prefix so other Aether apps can consume it.
#
# Layout (PREFIX defaults to /usr/local):
#   $PREFIX/share/aether-ui/aether_ui.ae   The DSL module; aetherc finds it via --lib
#   $PREFIX/lib/aether-ui/                 Backend .c/.m sources + headers for this host
#   $PREFIX/bin/aether-ui-build            Wrapper that compiles consumer .ae apps
#
# Usage:
#   ./install.sh                       Install to /usr/local (uses sudo if needed)
#   ./install.sh --prefix=$HOME/.local Install to a user prefix (no sudo)
#   ./install.sh --uninstall           Remove an existing install
#   ./install.sh --dry-run             Print what would happen, don't do it

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PREFIX="${PREFIX:-/usr/local}"
UNINSTALL=0
DRY_RUN=0

for arg in "$@"; do
    case "$arg" in
        --prefix=*) PREFIX="${arg#--prefix=}" ;;
        --uninstall) UNINSTALL=1 ;;
        --dry-run) DRY_RUN=1 ;;
        -h|--help) sed -n '2,/^$/p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown arg: $arg" >&2; exit 1 ;;
    esac
done

SHARE_DIR="$PREFIX/share/aether-ui"
LIB_DIR="$PREFIX/lib/aether-ui"
BIN_DIR="$PREFIX/bin"
WRAPPER="$BIN_DIR/aether-ui-build"

OS="$(uname -s)"
case "$OS" in
    Darwin)
        PLATFORM_FILES=(aether_ui_macos.m aether_ui_system_extras.c aether_ui_system_extras.h aether_ui_backend.h)
        ;;
    Linux)
        PLATFORM_FILES=(aether_ui_gtk4.c aether_ui_system_extras.c aether_ui_system_extras.h aether_ui_sni.c aether_ui_sni.h aether_ui_backend.h)
        ;;
    MINGW*|MSYS*|CYGWIN*)
        PLATFORM_FILES=(aether_ui_win32.c aether_ui_system_extras.c aether_ui_system_extras.h aether_ui_test_server.c aether_ui_test_server.h aether_ui_backend.h)
        ;;
    *) echo "Error: Unsupported platform '$OS'" >&2; exit 1 ;;
esac

NEED_SUDO=""
if [ "$DRY_RUN" -eq 0 ]; then
    probe="$PREFIX"
    while [ ! -d "$probe" ]; do probe="$(dirname "$probe")"; done
    if [ ! -w "$probe" ]; then
        if command -v sudo >/dev/null 2>&1; then
            NEED_SUDO="sudo"
            echo "Note: $PREFIX is not writable by $(whoami); will use sudo."
        else
            echo "Error: $PREFIX is not writable and sudo is not available." >&2
            exit 1
        fi
    fi
fi

run() {
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "DRY-RUN: $*"
    else
        $NEED_SUDO "$@"
    fi
}

if [ "$UNINSTALL" -eq 1 ]; then
    echo "Uninstalling aether-ui from $PREFIX"
    run rm -rf "$SHARE_DIR"
    run rm -rf "$LIB_DIR"
    run rm -f "$WRAPPER"
    echo "Done."
    exit 0
fi

echo "Installing aether-ui to $PREFIX (platform: $OS)"

run mkdir -p "$SHARE_DIR" "$LIB_DIR" "$BIN_DIR"

run install -m 644 "$SCRIPT_DIR/aether_ui.ae" "$SHARE_DIR/aether_ui.ae"

for f in "${PLATFORM_FILES[@]}"; do
    run install -m 644 "$SCRIPT_DIR/$f" "$LIB_DIR/$f"
done

TMP_WRAPPER="$(mktemp)"
cat > "$TMP_WRAPPER" <<WRAPPER_EOF
#!/bin/bash
# aether-ui-build — compile an Aether UI app against the system-installed aether-ui.
# Auto-generated by aether-ui install.sh. Re-run install.sh to refresh.
set -e

AETHER_UI_SHARE="$SHARE_DIR"
AETHER_UI_LIB="$LIB_DIR"
AETHERC="aetherc"

AETHER_INCLUDES="-I/usr/local/include/aether/runtime -I/usr/local/include/aether/runtime/actors -I/usr/local/include/aether/std -I/usr/local/include/aether/std/collections"
AETHER_LIB_PATH="/usr/local/lib/aether"

SOURCE="\${1:?Usage: \$0 <source.ae> [output_binary]}"
OUTPUT="\${2:-\$(basename "\$SOURCE" .ae)}"
C_FILE="\${OUTPUT}.c"

echo "Compiling \$SOURCE -> \$C_FILE"
"\$AETHERC" --lib "\$AETHER_UI_SHARE" "\$SOURCE" "\$C_FILE"

OS="\$(uname -s)"
case "\$OS" in
    Darwin)
        echo "Platform: macOS (AppKit)"
        clang -O0 -g -fobjc-arc \\
            -I"\$AETHER_UI_LIB" \\
            \$AETHER_INCLUDES \\
            "\$C_FILE" "\$AETHER_UI_LIB/aether_ui_macos.m" \\
            "\$AETHER_UI_LIB/aether_ui_system_extras.c" \\
            -L"\$AETHER_LIB_PATH" -laether \\
            -o "\$OUTPUT" \\
            -framework AppKit -framework Foundation -framework QuartzCore -pthread -lm
        ;;
    Linux)
        if ! pkg-config --exists gtk4 2>/dev/null; then
            echo "Error: GTK4 dev libraries not found." >&2; exit 1
        fi
        echo "Platform: Linux (GTK4)"
        LIBNOTIFY_CFLAGS=""; LIBNOTIFY_LIBS=""
        if pkg-config --exists libnotify 2>/dev/null; then
            LIBNOTIFY_CFLAGS="-DAEUI_HAVE_LIBNOTIFY=1 \$(pkg-config --cflags libnotify)"
            LIBNOTIFY_LIBS="\$(pkg-config --libs libnotify)"
        fi
        gcc -O0 -g -pipe \\
            \$(pkg-config --cflags gtk4) \\
            -I"\$AETHER_UI_LIB" \\
            \$AETHER_INCLUDES \\
            \$LIBNOTIFY_CFLAGS \\
            "\$C_FILE" "\$AETHER_UI_LIB/aether_ui_gtk4.c" \\
            "\$AETHER_UI_LIB/aether_ui_system_extras.c" \\
            "\$AETHER_UI_LIB/aether_ui_sni.c" \\
            -L"\$AETHER_LIB_PATH" -laether \\
            -o "\$OUTPUT" \\
            -pthread -lm \$(pkg-config --libs gtk4) \$LIBNOTIFY_LIBS
        ;;
    MINGW*|MSYS*|CYGWIN*)
        echo "Platform: Windows (native Win32)"
        OUT_EXE="\${OUTPUT}.exe"
        [[ "\$OUTPUT" != *.exe ]] && ACTUAL_OUT="\$OUT_EXE" || ACTUAL_OUT="\$OUTPUT"
        gcc -O2 -g -pipe \\
            -I"\$AETHER_UI_LIB" \\
            \$AETHER_INCLUDES \\
            "\$C_FILE" "\$AETHER_UI_LIB/aether_ui_win32.c" \\
            "\$AETHER_UI_LIB/aether_ui_test_server.c" \\
            "\$AETHER_UI_LIB/aether_ui_system_extras.c" \\
            -L"\$AETHER_LIB_PATH" -laether \\
            -o "\$ACTUAL_OUT" \\
            -luser32 -lgdi32 -lgdiplus -lcomctl32 -lcomdlg32 \\
            -lshell32 -lole32 -luuid -ldwmapi -luxtheme \\
            -lws2_32 -pthread -lm
        OUTPUT="\$ACTUAL_OUT"
        ;;
    *) echo "Error: Unsupported platform '\$OS'." >&2; exit 1 ;;
esac

echo "Built: \$OUTPUT"
WRAPPER_EOF

run install -m 755 "$TMP_WRAPPER" "$WRAPPER"
rm -f "$TMP_WRAPPER"

echo
echo "Done. Aether UI installed to $PREFIX"
echo
echo "From another Aether app:"
echo "  import aether_ui            # in your .ae source"
echo "  $WRAPPER your_app.ae [out]  # build it"
echo
echo "Or call aetherc/gcc directly:"
echo "  pass  --lib $SHARE_DIR  to aetherc so 'import aether_ui' resolves"
echo "  add   -I$LIB_DIR  and the platform sources from there to your link line"
